kind: Pod
apiVersion: v1
metadata:
  name: invoker
  labels:
    app: invoker
spec:
  volumes:
    - name: manifest-data
      configMap:
        name: manifest-config
    - name: envoy-data
      emptyDir: {}
    - name: secret-volume
      secret:
        secretName: sleep-secret
        optional: true

  containers:
    - name: sleep
      image: curlimages/curl
      command: ["/bin/sleep", "3650d"]
      volumeMounts:
      - mountPath: /etc/sleep/tls
        name: secret-volume
      - name: envoy-data
        mountPath: /etc/envoy
      - name: manifest-data
        mountPath: /etc/faas

    - name: envoy
      image: docker.io/envoyproxy/envoy:v1.17-latest
      ports:
        - name: http
          containerPort: 18000
          protocol: TCP
      resources: { }
      volumeMounts:
        - name: envoy-data
          mountPath: /etc/envoy
    - name: invoker
      image: materialized-invoker
      #      TODO: pull from manifest.yaml
      env:
        - name: AUTHZ_BASE_URL
          value: http://authz:8081
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP
      volumeMounts:
        - name: manifest-data
          mountPath: /etc/faas
  initContainers:
    - name: envoy-init
      image: docker.io/kettil/faas-envoy-init
      env:
        - name: MANIFEST_FILE
          value: /etc/faas/manifest.yaml
        - name: ENVOY_CONFIG_FILE
          value: /etc/envoy/envoy.yaml
      volumeMounts:
        - name: manifest-data
          mountPath: /etc/faas
        - name: envoy-data
          mountPath: /etc/envoy
