kind: Pod
apiVersion: v1
metadata:
  name: invoker
  labels:
    app: invoker
spec:
  volumes:
    - name: manifest-data
      configMap:
        name: manifest-config
  containers:
    - name: invoker
      image: materialized-invoker
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP
      volumeMounts:
        - name: manifest-data
          mountPath: /etc/faas
