apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - invoker-pod.yaml
  - invoker-service.yaml

configMapGenerator:
- name: manifest-configmap
  files:
  - manifest.yaml
- name: envoy-configmap
  files:
    - envoy.yaml
