apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: work
build:
  artifacts:
  - image: docker.io/kettil/materialized-invoker
    docker:
      dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
    - kube/kustomize
